"""Check an extracted local bundle without importing or running its contents."""
import argparse
import hashlib
import json
from pathlib import Path, PurePosixPath


def verify(directory):
    root=Path(directory).resolve()
    manifest=json.loads((root/'package_manifest.json').read_text(encoding='utf-8'))
    if manifest.get('format')!=1 or manifest.get('purpose')!='local-test-only':
        raise ValueError('Unsupported bundle manifest')
    files=manifest.get('files')
    if not isinstance(files,dict) or not files: raise ValueError('Missing file list')
    checked=[]
    for name,expected in files.items():
        relative=PurePosixPath(name)
        if relative.is_absolute() or '..' in relative.parts or '\\' in name or ':' in name:
            raise ValueError('Unsafe manifest path')
        path=root.joinpath(*relative.parts).resolve()
        if not path.is_relative_to(root): raise ValueError('File escapes bundle directory')
        actual=hashlib.sha256(path.read_bytes()).hexdigest()
        checked.append({'file':name,'match':actual==expected})
    # Unexpected Python code can shadow expected imports. Runtime-generated bytecode
    # and run diagnostics are permitted; other additions invalidate the bundle.
    allowed=set(files)|{'package_manifest.json'}
    unexpected=[p.relative_to(root).as_posix() for p in root.rglob('*') if p.is_file()
                and p.relative_to(root).as_posix() not in allowed
                and '__pycache__' not in p.relative_to(root).parts
                and p.relative_to(root).parts[0]!='run-logs']
    return {'passed':all(x['match'] for x in checked) and not unexpected,
            'checks':checked,'unexpected_files':sorted(unexpected),
            'scope':'Integrity against supplied manifest; not a publisher signature'}


def main():
    parser=argparse.ArgumentParser(); parser.add_argument('directory',type=Path)
    args=parser.parse_args()
    try: result=verify(args.directory)
    except (OSError,ValueError,TypeError) as error:
        result={'passed':False,'error':str(error)}
    print(json.dumps(result,indent=2))
    raise SystemExit(0 if result['passed'] else 1)


if __name__=='__main__': main()
